require('vim._core.ui2').enable()
require('danyelkeddah.options')
require('danyelkeddah.keymaps')
require('danyelkeddah.autocmds')
require('danyelkeddah.pack')
require('danyelkeddah.lsp')
require('danyelkeddah.theme')
