# Basic Settings
if-shell '[ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]' {
    set -g prefix C-a
    unbind C-b
    bind C-a send-prefix
} {
    set -g prefix C-b
    unbind C-a
    bind C-b send-prefix
}
set -g default-terminal "${TERM}"
set-option -ag terminal-overrides ",xterm*:Tc" # true colors
set-option -g detach-on-destroy off
set-option -s escape-time 0 # address vim mode switching delay (http://superuser.com/a/252717/65504)
set-option -g history-limit 10000 # increase scrollback buffer size
set-option -g display-time 2000 # tmux messages are displayed for 1 seconds
set-option -g focus-events on # Focus events enabled for terminals that support them
set-option -g base-index 1 # start index 1
set-option -g pane-base-index 1 # start index 1
set-option -g renumber-windows on # start index 1
set-window-option -g pane-base-index 1 # start index 1
set-option -g mouse on # Allow the mouse to resize windows and  # <C-b>leftselect tabs
set-option -g allow-rename off
set-option -g status-position top
set-window-option -g mode-keys vi
# set-option remain-on-exit on
##
# Undercurl support
set-option -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set-option -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
 # Terminal features
set-option -ga terminal-overrides ",xterm-256color-italic*:Tc"
set-option -as terminal-features ",xterm-256color-italic:RGB"


# Bindings
# general bindings
# bind-key C-p previous-window
# <C-b>right # <C-b>left# bind-key C-n next-window
# bind-key Space set status
# bind-key a switch-client -l

bind-key x kill-pane

# Resize panes
bind-key J resize-pane -D 10
bind-key K resize-pane -U 10
bind-key H resize-pane -L 10
bind-key L resize-pane -R 10

bind-key j select-pane -D 
bind-key k select-pane -U 
bind-key h select-pane -L 
bind-key l select-pane -R 

bind-key R source-file ~/.config/tmux/tmux.conf \; display-message "~/.tmux.conf reloaded"
bind-key -r F new-window t
bind-key -r D run-shell "t ~/.dotfiles" #dotfiles
bind-key -r V run-shell "t ~/.dotfiles/roles/nvim/files" #nvim
bind-key -r O run-shell "t ~/second-brain" # secon brain
# bind -r G popup -d '#{pane_current_path}' -E -w 90% -h 90% lazygit #lazygit
# bind -r H popup -E -w 90% -h 90% gh dash #github dash
# bind -r T popup -d '#{pane_current_path}' -E -w 90% -h 90% # terminal
bind-key "|" split-window -h -c "#{?pane_path,#{s@^file.//@@:pane_path},#{pane_current_path}}"
bind-key "-" split-window -v -c "#{?pane_path,#{s@^file.//@@:pane_path},#{pane_current_path}}"

bind-key -n C-S-Left set status on\; swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right set status on\; swap-window -t +1\; select-window -t +1

source "~/.config/tmux/themes/catppuccin-mocha-theme.tmux.conf"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "janoamaral/tokyo-night-tmux"

run '~/.config/tmux/plugins/tpm/tpm'

