return {
    cmd = { 'tailwindcss-language-server', '--stdio' },
    root_markers = { 'package.json', '.git' },
    filetypes = {
        -- html
        'aspnetcorerazor',
        'astro',
        'astro-markdown',
        'blade',
        'clojure',
        'django-html',
        'htmldjango',
        'edge',
        'eelixir', -- vim ft
        'elixir',
        'ejs',
        'erb',
        'eruby', -- vim ft
        'gohtml',
        'gohtmltmpl',
        'haml',
        'handlebars',
        'hbs',
        'html',
        'htmlangular',
        'html-eex',
        'heex',
        'jade',
        'leaf',
        'liquid',
        'markdown',
        'mdx',
        'mustache',
        'njk',
        'nunjucks',
        'php',
        'razor',
        'slim',
        'twig',
        -- css
        'css',
        'less',
        'postcss',
        'sass',
        'scss',
        'stylus',
        'sugarss',
        -- js
        'javascript',
        'javascriptreact',
        'reason',
        'rescript',
        'typescript',
        'typescriptreact',
        -- mixed
        'vue',
        'svelte',
        'templ',
    },
    settings = {
        tailwindCSS = {
            validate = true,
            lint = {
                cssConflict = 'warning',
                invalidApply = 'error',
                invalidScreen = 'error',
                invalidVariant = 'error',
                invalidConfigPath = 'error',
                invalidTailwindDirective = 'error',
                recommendedVariantOrder = 'warning',
            },
            classAttributes = {
                'class',
                'className',
                'class:list',
                'classList',
                'ngClass',
                '.*[cC]lassName$',
                '.*ClassName',
            },
            includeLanguages = {
                eelixir = 'html-eex',
                eruby = 'erb',
                templ = 'html',
                htmlangular = 'html',
            },
            experimental = {
                classRegex = {
                    { 'tv\\(([^)]*)\\)', '[\'"`]([^\'"`;]*).*?[\'"`]' },
                    { 'tv\\(([^)]*)\\)', '`([^`]*)`' },
                    { 'tv\\(([^)]*)\\)', '"([^"]*)"' },
                    { 'tv\\(([^)]*)\\)', "'([^']*)'" },
                    { 'tv\\(.*\\).*\\(([^)]*)\\)', '["\']([^"\']*)["\']' },
                    { '([a-zA-Z0-9_-]*[cC]lassName)\\s*=\\s*["\']([^"\']*)["\']', '([^"\'\\s]*)' },
                },
            },
        },
    },
}
