return {
    dap = {
        Stopped = { ' ', 'DiagnosticWarn', 'DapStoppedLine' },
        Breakpoint = ' ',
        BreakpointCondition = ' ',
        BreakpointRejected = { ' ', 'DiagnosticError' },
        LogPoint = '.>',
    },
    mason = {
        PackagePending = ' ',
        PackageInstalled = '󰄳 ',
        PackageUninstalled = ' 󰚌',
    },
    ui = {
        Vim = '',
        Astric = '',
        ArrowCircleDown = '',
        ArrowCircleLeft = '',
        ArrowCircleRight = '',
        ArrowCircleUp = '',
        BoldArrowDown = '',
        BoldArrowLeft = '',
        BoldArrowRight = '',
        BoldArrowUp = '',
        BoldClose = '',
        BoldDividerLeft = '',
        BoldDividerRight = '',

        BookMark = '',
        BoxChecked = '',
        Bug = '',
        Stacks = '',
        Scopes = '',
        Watches = '',
        DebugConsole = '',
        Calendar = '',
        Check = '',
        ChevronRight = '>',
        ChevronShortDown = '',
        ChevronShortLeft = '',
        ChevronShortRight = '',
        ChevronShortUp = '',
        Circle = '',
        Close = '',
        CloudDownload = '',
        Code = '',
        Comment = '',
        Dashboard = '',
        DividerLeft = '',
        DividerRight = '',
        DoubleChevronRight = '»',
        Ellipsis = '',
        EmptyFolder = '',
        EmptyFolderOpen = '',
        File = '',
        FileSymlink = '',
        Files = '',
        FindFile = '',
        FindText = '',
        FileModified = '',
        Fire = '',
        Folder = '',
        FolderOpen = '',
        FolderSymlink = '',
        Forward = '',
        Gear = '',
        History = '',
        Lightbulb = '',
        LineLeft = '▏',
        LineMiddle = '│',
        LastIndentMarker = '└',
        BoldLineLeft = '▎',
        ThickLineMiddle = '┃',
        List = '',
        Lock = '',
        NewFile = '',
        Note = '',
        Package = '',
        Pencil = '',
        Plus = '',
        Project = '',
        Search = '',
        SignIn = '',
        SignOut = '',
        Tab = '',
        Table = '',
        Target = '󰀘',
        Telescope = '',
        Text = '',
        Tree = '',
        Triangle = '契',
        TriangleShortArrowDown = '',
        TriangleShortArrowLeft = '',
        TriangleShortArrowRight = '',
        TriangleShortArrowUp = '',
        Time = '',
    },
    diagnostics = {
        Error = ' ',
        Warn = ' ',
        Hint = ' ',
        Info = ' ',
        BoldError = '',
        BoldWarning = '',
        Warning = '',
        BoldInformation = '',
        Information = '',
        BoldQuestion = '',
        Question = '',
        BoldHint = '',
        Debug = '',
        Trace = '✎',
        Dot = '●',
    },
    git = {
        BoldAdded = ' ',
        BoldModified = ' ',
        BoldRemoved = ' ',
        BoldDeleted = ' ',
        Added = '',
        Modified = '',
        Removed = '',
        Deleted = '',
        Ignored = '◌',
        Renamed = '',
        Staged = '',
        Unmerged = '',
        Unstaged = '',
        Untracked = '',
        Diff = '',
        Repo = '',
        Octoface = '',
        Branch = '',
        TopDelete = '‾',
    },
    kinds = {
        Array = ' ',
        Boolean = ' ',
        Class = ' ',
        Color = ' ',
        Constant = ' ',
        Constructor = ' ',
        Copilot = ' ',
        Enum = ' ',
        EnumMember = ' ',
        Event = ' ',
        Field = ' ',
        File = ' ',
        Folder = ' ',
        Function = ' ',
        Interface = ' ',
        Key = ' ',
        Keyword = ' ',
        Method = ' ',
        Module = ' ',
        Namespace = ' ',
        Null = ' ',
        Number = ' ',
        Object = ' ',
        Operator = ' ',
        Package = ' ',
        Property = ' ',
        Reference = ' ',
        Snippet = ' ',
        String = ' ',
        Struct = ' ',
        Text = ' ',
        TypeParameter = ' ',
        Unit = ' ',
        Value = ' ',
        Variable = ' ',
    },
    misc = {
        Robot = 'ﮧ',
        Squirrel = '',
        Tag = '',
        Watch = '',
        Smiley = '',
        Package = '',
        CircuitBoard = '',
    },
    kind = {
        Namespace = '󰌗',
        Text = '󰉿',
        Method = '󰆧',
        Function = '󰆧',
        Constructor = '',
        Field = '󰜢',
        Variable = '󰀫',
        Class = '󰠱',
        Interface = '',
        Module = '',
        Property = '󰜢',
        Unit = '󰑭',
        Value = '󰎠',
        Enum = '',
        Keyword = '󰌋',
        Snippet = '',
        Color = '󰏘',
        File = '󰈚',
        Reference = '󰈇',
        Folder = '󰉋',
        EnumMember = '',
        Constant = '󰏿',
        Struct = '󰙅',
        Event = '',
        Operator = '󰆕',
        TypeParameter = '󰊄',
        Table = '',
        Object = '󰅩',
        Tag = '',
        Array = '[]',
        Boolean = '',
        Number = '',
        Null = '󰟢',
        String = '󰉿',
        Calendar = '',
        Watch = '󰥔',
        Package = '',
        Copilot = '',
        Codeium = '',
        TabNine = '',
    },
    devicons = {
        default_icon = {
            icon = '󰈚',
            name = 'Default',
        },

        c = {
            icon = '',
            name = 'c',
        },

        css = {
            icon = '',
            name = 'css',
        },

        dart = {
            icon = '',
            name = 'dart',
        },

        deb = {
            icon = '',
            name = 'deb',
        },

        Dockerfile = {
            icon = '',
            name = 'Dockerfile',
        },

        html = {
            icon = '',
            name = 'html',
        },

        jpeg = {
            icon = '󰉏',
            name = 'jpeg',
        },

        jpg = {
            icon = '󰉏',
            name = 'jpg',
        },

        js = {
            icon = '󰌞',
            name = 'js',
        },

        kt = {
            icon = '󱈙',
            name = 'kt',
        },

        lock = {
            icon = '󰌾',
            name = 'lock',
        },

        lua = {
            icon = '',
            name = 'lua',
        },

        mp3 = {
            icon = '󰎆',
            name = 'mp3',
        },

        mp4 = {
            icon = '',
            name = 'mp4',
        },

        out = {
            icon = '',
            name = 'out',
        },

        png = {
            icon = '󰉏',
            name = 'png',
        },

        py = {
            icon = '',
            name = 'py',
        },

        ['robots.txt'] = {
            icon = '󰚩',
            name = 'robots',
        },

        toml = {
            icon = '',
            name = 'toml',
        },

        ts = {
            icon = '󰛦',
            name = 'ts',
        },

        ttf = {
            icon = '',
            name = 'TrueTypeFont',
        },

        rb = {
            icon = '',
            name = 'rb',
        },

        rpm = {
            icon = '',
            name = 'rpm',
        },

        vue = {
            icon = '󰡄',
            name = 'vue',
        },

        woff = {
            icon = '',
            name = 'WebOpenFontFormat',
        },

        woff2 = {
            icon = '',
            name = 'WebOpenFontFormat2',
        },

        xz = {
            icon = '',
            name = 'xz',
        },

        zip = {
            icon = '',
            name = 'zip',
        },
    },
}
