# Reference: https://github.com/catppuccin/tmux/blob/main/docs/reference/configuration.md
# Color Palette: https://catppuccin.com/palette/

set -g @plugin 'catppuccin/tmux#v2.1.2'


set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set-option -g status-right ""
set-option -g status-left ""
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_current_number_color "#{@thm_blue}"
set -g @catppuccin_status_background "default"
